apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-demo-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: eks-demo-app
  template:
    metadata:
      labels:
        app: eks-demo-app
    spec:
      containers:
        - name: eks-demo-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.container.port }}
